# Thanks to https://github.com/codecov. Got this script from there.
language: c
sudo: required

before_install:
  - sudo apt-get install gfortran

script:
  - cd src
  - gfortran -fprofile-arcs -ftest-coverage -c mod_data.f90
  - gfortran -fprofile-arcs -ftest-coverage -c mod_io.f90
  - gfortran -fprofile-arcs -ftest-coverage -c mod_xsec.f90
  - gfortran -fprofile-arcs -ftest-coverage -c mod_nodal.f90
  - gfortran -fprofile-arcs -ftest-coverage -c mod_cmfd.f90
  - gfortran -fprofile-arcs -ftest-coverage -c mod_th.f90
  - gfortran -fprofile-arcs -ftest-coverage -c mod_trans.f90
  - gfortran -fprofile-arcs -ftest-coverage -c mod_control.f90
  - gfortran -fprofile-arcs -ftest-coverage -c ADPRES.f90
  - gfortran -fprofile-arcs -ftest-coverage *.o -o adpres
  - ./adpres /home/travis/build/imronuke/ADPRES/smpl/static/IAEA3Ds
